# Generated by Django 4.0.4 on 2022-08-31 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie *',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Couleur')),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleur',
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Marque d'objets")),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
            },
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sous-Catégorie *')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objets.categorie', verbose_name="Catégorie de l'objet")),
            ],
            options={
                'verbose_name': 'Sous-Catégorie',
                'verbose_name_plural': 'Sous-Catégories',
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Désignation')),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Statut',
                'verbose_name_plural': 'Statuts',
            },
        ),
        migrations.CreateModel(
            name='TitreObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Désigantion')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objets.souscategorie', verbose_name='Type associé')),
            ],
            options={
                'verbose_name': 'TitreObjet',
                'verbose_name_plural': 'TitreObjets',
            },
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_action', models.DateField(verbose_name='Date perte/retrouvé')),
                ('is_public', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objets.categorie', verbose_name='Catégorie')),
                ('couleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objets.couleur', verbose_name='Couleur')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marque', to='objets.marque')),
                ('souscategorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='souscategorie', to='objets.souscategorie', verbose_name="Sous-Categorie d'objet")),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objets.statut', verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Objet',
                'verbose_name_plural': 'Objets',
            },
        ),
        migrations.CreateModel(
            name='ModifierObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.TextField(verbose_name='Changement effetué')),
                ('confirm', models.BooleanField(default=False, verbose_name='Modification Confirmer')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objets.objet', verbose_name='Objet')),
            ],
            options={
                'verbose_name': 'ModifierObjet',
                'verbose_name_plural': 'ModeifierObjets',
            },
        ),
        migrations.AddField(
            model_name='marque',
            name='souscategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objets.souscategorie', verbose_name='SousCatégorie'),
        ),
        migrations.CreateModel(
            name='ImageObjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Titre de l'image")),
                ('image', models.ImageField(upload_to='objet/')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objets.objet', verbose_name='Objet')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
